sudo: false
language: node_js
node_js:
 - "8"
before_install:
 - 'npm install -g npm@6'
cache:
  directories:
    - MigrantHub/client/node_modules
    - MigrantHub/server/node_modules
install:
  - npm install -g codecov
env:
  - CODECOV_TOKEN=229d2013-1dfc-4b1a-8606-a2fc3464d58d
jobs:
  include:
    - script: cd MigrantHub/client && npm install && npm run coverage && codecov
    - script: cd MigrantHub/server && npm install && npm run coverage && codecov
