version: '3'
services:
  server:
    build: .
    ports:
      - "80:5000"
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 5000
  db:
    image: mongo:latest
    restart: always
    volumes:
      - dbdata:/data/db
  service_rating_model:
    build:
      context: ./data_models/Service_Rating_Model
      dockerfile: Service_Recommender/Dockerfile
    ports:
      - "8060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  service_recommender:
    build:
      context: ./data_models/Service_Recommender
      dockerfile: Service_Recommender/Dockerfile
    ports:
      - "8128:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
volumes:
  dbdata: