version: '3'
services:
  server:
    build: .
    restart: always
    container_name: server
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 5000
  db:
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - dbdata:/data/db
  service_rating_model:
    build:
      context: ./data_models/Service_Rating_Model
      dockerfile: Service_Recommender/Dockerfile
    ports:
      - "8060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  service_recommender:
    build:
      context: ./data_models/Service_Recommender
      dockerfile: Service_Recommender/Dockerfile
    ports:
      - "8128:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - /var/discourse/:/var/discourse/
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - NGINX_HOST=programmedby.me
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
volumes:
  dbdata: